import csv

data_table = [
    {
        "Norme/Réglementation": "ISO/IEC 27001",
        "Contexte": "Norme internationale pour un Système de Management de la Sécurité de l’Information (SMSI)",
        "Objectifs Principaux": "Confidentialité, intégrité, disponibilité des données",
        "Exigences Clés": "Politique de sécurité, gestion des risques, audits, amélioration continue",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Modérée",
        "Coût": "Élevé",
        "Pénalités": "Aucune pénalité légale directe",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (typique pour toute org. orientée data)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 27002",
        "Contexte": "Guide de bonnes pratiques, extension de l’ISO 27001",
        "Objectifs Principaux": "Définir et maintenir des contrôles de sécurité",
        "Exigences Clés": "Classification des actifs, gestion des accès, mesures physiques et logiques",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Faible",
        "Coût": "Modéré",
        "Pénalités": "Pas de sanctions légales directes",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Impact important mais pas critique (dépend du degré d’IT utilisé)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 27005",
        "Contexte": "Norme pour la gestion des risques en sécurité de l’information",
        "Objectifs Principaux": "Identification, analyse, traitement des risques",
        "Exigences Clés": "Méthodologie structurée pour évaluer et hiérarchiser les risques",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Aucune pénalité légale directe",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (si l’entreprise est fortement digitalisée)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 27017",
        "Contexte": "Sécurité de l’information pour le cloud",
        "Objectifs Principaux": "Orientée services cloud et virtualisation",
        "Exigences Clés": "Contrôles spécifiques au cloud, répartition des responsabilités client/fournisseur",
        "Secteur Concerné": "Fournisseurs et clients de services cloud",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Pas de sanctions légales directes",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (souvent critique en environnement cloud)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 27018",
        "Contexte": "Protection des données personnelles dans les environnements cloud publics",
        "Objectifs Principaux": "Vie privée, confidentialité des données personnelles",
        "Exigences Clés": "Consentement, anonymisation, audits, transparence",
        "Secteur Concerné": "Fournisseurs cloud, entreprises manipulant données perso",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Aucune sanction légale directe ; soutient la conformité RGPD",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (pour la plupart des acteurs cloud)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 27701",
        "Contexte": "Extension de l’ISO 27001 pour la gestion de la vie privée",
        "Objectifs Principaux": "Conformité RGPD, protection de la privacy",
        "Exigences Clés": "SMSI intégré, rôles et responsabilités, PIA (Privacy Impact Assessment)",
        "Secteur Concerné": "Tous secteurs traitant des données personnelles",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Pas de sanctions directes mais facilite la conformité RGPD",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (surtout si data-driven)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 22301",
        "Contexte": "Gestion de la continuité d’activité",
        "Objectifs Principaux": "Résilience organisationnelle en cas d’incidents majeurs",
        "Exigences Clés": "Plan de continuité, analyses d’impact, tests réguliers",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Aucune sanction légale directe",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Impact important mais pas critique (si l’activité peut partiellement continuer)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 31000",
        "Contexte": "Cadre générique pour la gestion des risques",
        "Objectifs Principaux": "Identifier, analyser, traiter tout type de risque",
        "Exigences Clés": "Approche systématique et globale du risk management",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Faible",
        "Coût": "Modéré",
        "Pénalités": "Pas de sanctions légales directes",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Variable selon l’activité (souvent impact important)"
    },
    {
        "Norme/Réglementation": "ISO/IEC 62443",
        "Contexte": "Normes pour la sécurité des systèmes de contrôle industriel (ICS/SCADA)",
        "Objectifs Principaux": "Protéger les infrastructures industrielles et critiques",
        "Exigences Clés": "Segmentation réseau, gestion des accès, surveillance continue",
        "Secteur Concerné": "Industrie, énergie, transport, OIV",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Non spécifié légalement, souvent requis par contrats",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (secteur industriel)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (dans l’industrie automatisée)"
    },
    {
        "Norme/Réglementation": "COBIT 2019 (ISACA)",
        "Contexte": "Cadre de gouvernance IT et de management des risques",
        "Objectifs Principaux": "Aligner IT et objectifs métier, optimiser la gouvernance",
        "Exigences Clés": "Processus IT, pilotage, indicateurs et audits",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Aucune sanction légale directe",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Impact important mais pas critique (selon la maturité IT)"
    },
    {
        "Norme/Réglementation": "NIST SP 800-53 (USA)",
        "Contexte": "Contrôles de sécurité obligatoires pour les SI fédéraux US",
        "Objectifs Principaux": "Catalogue de contrôles pour se conformer au FISMA",
        "Exigences Clés": "Contrôles d’accès, traçabilité, gestion des vulnérabilités",
        "Secteur Concerné": "Secteur public US, sous-traitants",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Retrait ou non-renouvellement de contrats gouvernementaux",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (contrats fédéraux)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (environnement gouvernemental critique)"
    },
    {
        "Norme/Réglementation": "NIST SP 800-37 (USA)",
        "Contexte": "Cadre de gestion des risques (Risk Management Framework)",
        "Objectifs Principaux": "Autorisation à opérer (ATO), gestion continue des risques",
        "Exigences Clés": "Catégorisation, sélection de contrôles, évaluation, suivi",
        "Secteur Concerné": "Secteur public US, sous-traitants",
        "Complexité": "Élevée",
        "Coût": "Modéré",
        "Pénalités": "Perte d’autorisation, sanctions contractuelles",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (souvent entités plus grandes)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "NIST Cybersecurity Framework",
        "Contexte": "Cadre volontaire adopté globalement, initialement pour infrastructures critiques US",
        "Objectifs Principaux": "Identifier, protéger, détecter, répondre, récupérer",
        "Exigences Clés": "Évaluation des risques, plan de réponse, surveillance",
        "Secteur Concerné": "Tous secteurs (international)",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Pas de sanctions légales directes",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (la majorité des structures critiques)"
    },
    {
        "Norme/Réglementation": "PCI DSS",
        "Contexte": "Norme de sécurité pour l’industrie des cartes de paiement",
        "Objectifs Principaux": "Sécuriser les données de cartes bancaires",
        "Exigences Clés": "Chiffrement, segmentation réseau, contrôles d’accès, audits réguliers",
        "Secteur Concerné": "Commerçants, banques, e-commerce",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes, retrait de l’agrément de paiement",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles, mais + fréquent pour > 50 employés (volume de transactions)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (systèmes de paiement)"
    },
    {
        "Norme/Réglementation": "RGPD (GDPR)",
        "Contexte": "Règlement européen sur la protection des données personnelles",
        "Objectifs Principaux": "Respect de la vie privée, droits des personnes",
        "Exigences Clés": "Consentement, droits d’accès, notification en cas de violation",
        "Secteur Concerné": "Toutes entreprises manipulant des données UE",
        "Complexité": "Élevée",
        "Coût": "Modéré",
        "Pénalités": "Amendes jusqu’à 20 M€ ou 4 % du CA mondial",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises (pas de seuil d’employés)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, si l’entreprise est data-driven ; sinon impact important"
    },
    {
        "Norme/Réglementation": "DORA (EU)",
        "Contexte": "Résilience opérationnelle numérique pour les institutions financières",
        "Objectifs Principaux": "Continuité d’activité, gestion des risques numériques",
        "Exigences Clés": "Tests de résilience, gestion des tiers, obligations de reporting",
        "Secteur Concerné": "Secteur financier dans l’UE",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Sanctions financières, restrictions d’activité",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (banques, fintech conséquentes)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, l’activité s’arrête sans SI (secteur bancaire très numérisé)"
    },
    {
        "Norme/Réglementation": "NIS2",
        "Contexte": "Directive européenne sur la sécurité des réseaux et de l’information (v2)",
        "Objectifs Principaux": "Renforcer la cybersécurité des services essentiels et OSE",
        "Exigences Clés": "Mesures techniques, audits, signalement d’incidents",
        "Secteur Concerné": "Infrastructures critiques, opérateurs de services essentiels",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Sanctions administratives et financières",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (souvent grosses infra)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (services critiques)"
    },
    {
        "Norme/Réglementation": "eIDAS",
        "Contexte": "Règlement européen sur l’identification électronique et services de confiance",
        "Objectifs Principaux": "Reconnaissance mutuelle des identités électroniques, signatures, etc.",
        "Exigences Clés": "Authentification forte, signature électronique qualifiée, horodatage",
        "Secteur Concerné": "Secteur public, prestataires de services de confiance",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes administratives, invalidation de signatures",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises manipulant la signature électronique",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (pour les services en ligne)"
    },
    {
        "Norme/Réglementation": "ePrivacy Directive",
        "Contexte": "Directive UE protégeant la confidentialité des communications électroniques",
        "Objectifs Principaux": "Encadrement des cookies, e-mail marketing, métadonnées",
        "Exigences Clés": "Consentement préalable, protection de la vie privée en ligne",
        "Secteur Concerné": "Fournisseurs de services en ligne, opérateurs télécom",
        "Complexité": "Modérée",
        "Coût": "Faible",
        "Pénalités": "Amendes administratives (souvent associées au RGPD)",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises (y compris TPE/PME web)",
        "Votre activité dépend-elle fortement des SI ?": "Impact important mais pas critique (majoritairement marketing / comm)"
    },
    {
        "Norme/Réglementation": "EBA Guidelines (ICT & Security)",
        "Contexte": "Lignes directrices de l’Autorité Bancaire Européenne",
        "Objectifs Principaux": "Sécuriser l’IT et la gestion des risques cyber dans le secteur bancaire",
        "Exigences Clés": "Politiques de sécurité, audits, rapports, plan de continuité",
        "Secteur Concerné": "Établissements financiers dans l’UE",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Sanctions financières via les régulateurs bancaires",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (banques, assurances, fintech structurées)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (institutions bancaires)"
    },
    {
        "Norme/Réglementation": "LPM (France)",
        "Contexte": "Loi imposant des mesures de cybersécurité aux OIV (Opérateurs d’Importance Vitale)",
        "Objectifs Principaux": "Protéger les infrastructures critiques françaises",
        "Exigences Clés": "Mesures techniques, audits, signalement des incidents, plan de sécurité",
        "Secteur Concerné": "Infrastructures critiques (énergie, santé, transport)",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Sanctions administratives, voire pénales",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (OIV sont souvent de grandes entités)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (distribution énergie, transport...)"
    },
    {
        "Norme/Réglementation": "Loi pour une République Numérique",
        "Contexte": "Loi française orientée vers la transparence, l’ouverture des données et la protection",
        "Objectifs Principaux": "Ouverture des données publiques, droits numériques, portabilité",
        "Exigences Clés": "Démarches d’ouverture de données, portabilité, transparence",
        "Secteur Concerné": "Secteur public, entreprises manipulant des données FR",
        "Complexité": "Faible",
        "Coût": "Faible",
        "Pénalités": "Amendes et sanctions administratives",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises en France",
        "Votre activité dépend-elle fortement des SI ?": "Impact limité ou important selon l’usage des données"
    },
    {
        "Norme/Réglementation": "CNIL (France)",
        "Contexte": "Règles et recommandations (délibérations, référentiels)",
        "Objectifs Principaux": "Garantie de la conformité RGPD, respect de la vie privée en France",
        "Exigences Clés": "Consentement, registres de traitement, DPO, formalités déclaratives",
        "Secteur Concerné": "Toutes entreprises gérant des données persos en France",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes financières pouvant atteindre 20 M€ ou 4 % du CA",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI si data critique (surtout data perso)"
    },
    {
        "Norme/Réglementation": "Projet de Loi Résilience (France)",
        "Contexte": "Proposition législative pour la résilience numérique",
        "Objectifs Principaux": "Continuité de service, plans de résilience, coordination en cas de crise",
        "Exigences Clés": "Exigences de redondance, organisation de crise, reporting",
        "Secteur Concerné": "Services critiques, opérateurs de services numériques",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Non défini (en cours d’élaboration)",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (secteurs critiques)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (forte dépendance)"
    },
    {
        "Norme/Réglementation": "CJIS Security Policy (USA)",
        "Contexte": "Politique de sécurité du FBI pour la protection des données de justice et de police",
        "Objectifs Principaux": "Confidentialité, intégrité, traçabilité des données policières",
        "Exigences Clés": "Contrôles d’accès, cryptographie, journalisation, authentification",
        "Secteur Concerné": "Justice, police, sous-traitants gouvernementaux US",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Perte de certification, actions légales",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (entités officielles, sous-traitants)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, activité s’arrête sans SI (systèmes de justice critiques)"
    },
    {
        "Norme/Réglementation": "CMMC (USA)",
        "Contexte": "Cybersecurity Maturity Model Certification pour les sous-traitants du DoD",
        "Objectifs Principaux": "Vérifier la maturité cyber des prestataires de la défense",
        "Exigences Clés": "Audits, contrôles basés sur NIST, certification progressive (Niveaux 1 à 5)",
        "Secteur Concerné": "Sous-traitants du Département de la Défense US",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Impossibilité d’obtenir des contrats DoD sans certification",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (entreprises de défense et ingénierie)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "FISMA (USA)",
        "Contexte": "Federal Information Security Management Act",
        "Objectifs Principaux": "Sécuriser et protéger les systèmes d’information fédéraux",
        "Exigences Clés": "Gouvernance, plans de sécurité, évaluations annuelles",
        "Secteur Concerné": "Agences fédérales US, sous-traitants",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Perte de financement, enquêtes légales",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (agences, gros marchés publics)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "FedRAMP (USA)",
        "Contexte": "Programme d’autorisation pour les services cloud du gouvernement fédéral US",
        "Objectifs Principaux": "Uniformiser l’évaluation et la surveillance continue de la sécurité cloud",
        "Exigences Clés": "Audit indépendant (3PAO), autorisation (ATO), revue continue",
        "Secteur Concerné": "Fournisseurs cloud du gouvernement US",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Retrait de l’autorisation FedRAMP et perte de contrats",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (fournisseurs cloud importants)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (environnement purement cloud)"
    },
    {
        "Norme/Réglementation": "HIPAA (USA)",
        "Contexte": "Health Insurance Portability and Accountability Act",
        "Objectifs Principaux": "Protection des données de santé (PHI)",
        "Exigences Clés": "Politiques de confidentialité, cryptage, audit logs",
        "Secteur Concerné": "Secteur santé US (hôpitaux, assurances, etc.)",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes pouvant aller jusqu’à plusieurs millions de dollars",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (mais souvent structures > 50 dans la santé)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (hôpitaux, cliniques digitalisées)"
    },
    {
        "Norme/Réglementation": "HITECH (USA)",
        "Contexte": "Renforcement de HIPAA, impose des notifications en cas de violations",
        "Objectifs Principaux": "Transparence accrue, notification rapide aux patients",
        "Exigences Clés": "Notification de faille, sanctions aggravées",
        "Secteur Concerné": "Secteur santé US (mêmes acteurs qu’HIPAA)",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes sévères, sanctions civiques et pénales",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles, souvent plus grandes structures",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (santé dépendante du numérique)"
    },
    {
        "Norme/Réglementation": "Sarbanes-Oxley Act Section 404",
        "Contexte": "Loi US sur la gouvernance d’entreprise et la transparence financière",
        "Objectifs Principaux": "Fiabiliser l’information financière, contrôles internes IT",
        "Exigences Clés": "Audit indépendant, reporting financier, traçabilité",
        "Secteur Concerné": "Entreprises cotées aux États-Unis",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes financières, voire peines pénales",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 250 employés (grandes entreprises cotées)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (ERP, systèmes financiers)"
    },
    {
        "Norme/Réglementation": "Basel III (Sécurité IT)",
        "Contexte": "Cadre bancaire international intégrant la gestion des risques (dont risques IT)",
        "Objectifs Principaux": "Assurer la stabilité financière, dont la résilience cyber",
        "Exigences Clés": "Stress tests, fonds propres, gestion des risques IT",
        "Secteur Concerné": "Banques et institutions financières internationales",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Sanctions réglementaires, pénalités financières",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 250 employés (grandes banques et filiales)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "PSD2 (UE)",
        "Contexte": "Directive européenne sur les services de paiement",
        "Objectifs Principaux": "Sécuriser les paiements en ligne, authentification forte (SCA)",
        "Exigences Clés": "API ouvertes, gestion des risques, cryptographie, Strong Customer Authentication",
        "Secteur Concerné": "Établissements de paiement, FinTech dans l’UE",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes en cas de non-conformité",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (même TPE fintech), mais souvent > 50 employés",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (plateformes de paiement)"
    },
    {
        "Norme/Réglementation": "BDSG (Allemagne)",
        "Contexte": "Loi allemande de protection des données, complément au RGPD",
        "Objectifs Principaux": "Protection renforcée des données et obligations spécifiques",
        "Exigences Clés": "Consentement, transferts limités, DPO, obligations d’information",
        "Secteur Concerné": "Entreprises opérant en Allemagne",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes administratives alignées RGPD",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI si data critique (équivalent RGPD)"
    },
    {
        "Norme/Réglementation": "UK Data Protection Act 2018",
        "Contexte": "Loi britannique post-RGPD, intégrant les principes du RGPD au Royaume-Uni",
        "Objectifs Principaux": "Maintenir des standards élevés de protection des données",
        "Exigences Clés": "Droits individuels, consentement, DPO, sanctions en cas de fuite",
        "Secteur Concerné": "Toute entreprise manipulant des données au Royaume-Uni",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes financières (jusqu’à 17,5 M£ ou 4 % CA)",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Impact important, voire critique, selon la dépendance SI"
    },
    {
        "Norme/Réglementation": "LGPD (Brésil)",
        "Contexte": "Lei Geral de Proteção de Dados, équivalent brésilien du RGPD",
        "Objectifs Principaux": "Protéger la vie privée des résidents brésiliens",
        "Exigences Clés": "Consentement, portabilité, notification, DPO, sanctions",
        "Secteur Concerné": "Toutes entreprises manipulant des données au Brésil",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes jusqu’à 2 % CA brésilien ou 50 M R$",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI si data critique"
    },
    {
        "Norme/Réglementation": "PIPL (Chine)",
        "Contexte": "Personal Information Protection Law, loi chinoise sur la protection des données perso",
        "Objectifs Principaux": "Réguler la collecte, l’utilisation et la protection des données personnelles",
        "Exigences Clés": "Consentement éclairé, transferts transfrontaliers restreints, audits",
        "Secteur Concerné": "Entreprises manipulant des données de résidents chinois",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes allant jusqu’à 5 % du CA annuel",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises opérant en Chine",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "Cybersecurity Law of China",
        "Contexte": "Loi encadrant la sécurité des réseaux et la localisation des données en Chine",
        "Objectifs Principaux": "Contrôler les infrastructures critiques et la gestion des données",
        "Exigences Clés": "Stockage local, audits fréquents, certification obligatoire",
        "Secteur Concerné": "Infrastructures critiques, entreprises en Chine",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes, suspension d’activité, blocage",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles, surtout grandes structures présentes en Chine",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (notamment en secteur critique)"
    },
    {
        "Norme/Réglementation": "PDPA (Singapour)",
        "Contexte": "Personal Data Protection Act : Cadre de protection des données à Singapour",
        "Objectifs Principaux": "Réguler collecte, usage et divulgation des données",
        "Exigences Clés": "Consentement, notification des fuites, mesures de sécurité",
        "Secteur Concerné": "Toutes entreprises manipulant des données à Singapour",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes jusqu’à 1 M SGD",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI si data centrale"
    },
    {
        "Norme/Réglementation": "POPIA (Afrique du Sud)",
        "Contexte": "Protection of Personal Information Act, loi de protection des données",
        "Objectifs Principaux": "Principes de licéité, consentement, sécurité et notification des fuites",
        "Exigences Clés": "DPO, transparence, obligations de sécurité",
        "Secteur Concerné": "Toutes entreprises manipulant des données en Afrique du Sud",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Amendes jusqu’à 10 M ZAR ou peine d’emprisonnement",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Impact important si dépendance data (souvent critique)"
    },
    {
        "Norme/Réglementation": "ANSSI Référentiels (France)",
        "Contexte": "Guides et labels de l’ANSSI pour la sécurité des SI, qualification de prestataires",
        "Objectifs Principaux": "Définir un haut niveau de sécurité pour l’État et les opérateurs critiques",
        "Exigences Clés": "Audit, homologation, PDIS, PRIS, PASSI, qualifications officielles",
        "Secteur Concerné": "Secteur public, OIV, prestataires d’infogérance, etc.",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Perte de qualification, sanctions administratives",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (surtout > 50 employés si prestataire)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "ENISA Cybersecurity Act (UE)",
        "Contexte": "Donne un mandat renforcé à l’ENISA et crée un cadre de certification cyber à l’UE",
        "Objectifs Principaux": "Établir des schémas de certification européens",
        "Exigences Clés": "Label européen de cybersécurité, exigences techniques et organisationnelles",
        "Secteur Concerné": "Secteur IT, fabricants, opérateurs cloud, produits et services TIC",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes administratives, retraits de certification",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (mais la certification vise souvent > 50 employés)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (fournisseurs TIC)"
    },
    {
        "Norme/Réglementation": "ePrivacy Regulation (UE, projet)",
        "Contexte": "Réglementation remplaçant la directive ePrivacy, à venir",
        "Objectifs Principaux": "Confidentialité des communications électroniques, usage des cookies",
        "Exigences Clés": "Consentement pour cookies, protection des métadonnées, obligations renforcées",
        "Secteur Concerné": "Fournisseurs de services en ligne, telco, entreprises UE",
        "Complexité": "Élevée",
        "Coût": "Modéré",
        "Pénalités": "Amendes administratives (proches RGPD)",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Impact important mais pas critique (variable selon le business)"
    },
    {
        "Norme/Réglementation": "ICS-CERT Guidelines (USA)",
        "Contexte": "Recommandations de l’ICS-CERT pour la sécurité des systèmes industriels",
        "Objectifs Principaux": "Protéger les infrastructures ICS contre les cybermenaces",
        "Exigences Clés": "Segmentation, correctifs, plans d’incident, durcissement",
        "Secteur Concerné": "Secteurs industriels et infrastructures critiques US",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Non spécifié légalement, pertes de contrats possibles",
        "Combien d’employés compte votre entreprise ?": "Plutôt > 50 employés (industrie, OIV)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "FIPS 140-3 (USA)",
        "Contexte": "Norme fédérale pour la validation de modules cryptographiques",
        "Objectifs Principaux": "Définir des niveaux de sécurité (1 à 4) et exiger une validation formelle",
        "Exigences Clés": "Certification cryptographique par des labos agréés (CMVP)",
        "Secteur Concerné": "Gouvernement US, fournisseurs de solutions cryptographiques",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Non-conformité = impossibilité de fournir au gouvernement",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (éditeurs solutions crypto)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, cryptographie critique si l’activité en dépend"
    },
    {
        "Norme/Réglementation": "ISAE 3402",
        "Contexte": "Norme internationale d’audit sur les contrôles internes des fournisseurs de services",
        "Objectifs Principaux": "Produire un rapport d’assurance sur l’efficacité des contrôles",
        "Exigences Clés": "Audit indépendant, rapport type I ou II, transparence vis-à-vis des clients",
        "Secteur Concerné": "Fournisseurs de services d’externalisation, BPO, data centers, etc.",
        "Complexité": "Modérée",
        "Coût": "Élevé",
        "Pénalités": "Pas de sanctions légales directes, impact business (perte de clients)",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (mais courante > 50 employés dans l’outsourcing)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI"
    },
    {
        "Norme/Réglementation": "SOC 2 (AICPA)",
        "Contexte": "Audit axé sur la sécurité, la disponibilité, l’intégrité, la confidentialité, la vie privée",
        "Objectifs Principaux": "Donner confiance sur les contrôles internes des prestataires cloud / SaaS",
        "Exigences Clés": "Audit indépendant, rapport d’attestation, évaluation des contrôles",
        "Secteur Concerné": "Prestataires de services cloud, hébergeurs, SaaS",
        "Complexité": "Modérée",
        "Coût": "Élevé",
        "Pénalités": "Pas de sanctions directes, mais nécessaire pour la crédibilité auprès des clients",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles (surtout > 50 employés chez les fournisseurs)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (services SaaS / Cloud)"
    },
    {
        "Norme/Réglementation": "TISAX (Allemagne)",
        "Contexte": "Standard de sécurité pour l’industrie automobile (Trusted Information Security Assessment Exchange)",
        "Objectifs Principaux": "Mutualiser l’évaluation de la sécurité entre constructeurs/fournisseurs",
        "Exigences Clés": "Audits, classification des informations, gestion des accès, plan de remédiation",
        "Secteur Concerné": "Constructeurs auto, sous-traitants (VDA, OEM)",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Retrait du label TISAX, perte de partenariats OEM",
        "Combien d’employés compte votre entreprise ?": "Moins de 50 à > 250 (variable, mais souvent mid-size ou grande)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (process auto connectés)"
    },
    {
        "Norme/Réglementation": "WLA-SCS",
        "Contexte": "World Lottery Association Security Control Standard",
        "Objectifs Principaux": "Sécuriser la gestion des loteries et jeux d’argent",
        "Exigences Clés": "Contrôles organisationnels, traçabilité, audits indépendants",
        "Secteur Concerné": "Opérateurs de loteries et jeux d’argent mondiaux",
        "Complexité": "Modérée",
        "Coût": "Modéré",
        "Pénalités": "Retrait de la certification WLA, impact réputationnel",
        "Combien d’employés compte votre entreprise ?": "Souvent > 50 employés (opérateurs de jeux)",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (jeux en ligne, tirage)"
    },
    {
        "Norme/Réglementation": "CCPA/CPRA (Californie, USA)",
        "Contexte": "Lois californiennes de protection de la vie privée",
        "Objectifs Principaux": "Transparence, opt-out, droits d’accès, suppression",
        "Exigences Clés": "Notification de la collecte, possibilité de refuser la vente de données",
        "Secteur Concerné": "Entreprises manipulant des données de résidents californiens",
        "Complexité": "Élevée",
        "Coût": "Élevé",
        "Pénalités": "Amendes jusqu’à 7 500 $ par violation intentionnelle, class actions",
        "Combien d’employés compte votre entreprise ?": "Toutes tailles d’entreprises",
        "Votre activité dépend-elle fortement des SI ?": "Oui, notre activité s’arrête sans SI (business data-driven)"
    }
]

# Descriptions textuelles associées à chaque loi (50 lignes, dans l’ordre).
descriptions = [
    "ISO/IEC 27001 : Cadre international pour établir un Système de Management de la Sécurité de l’Information (SMSI).",
    "ISO/IEC 27002 : Bonnes pratiques pour compléter 27001 (contrôles et organisation).",
    "ISO/IEC 27005 : Méthodologie structurée de gestion des risques cybersécurité.",
    "ISO/IEC 27017 : Mesures de sécurité supplémentaires pour les environnements cloud.",
    "ISO/IEC 27018 : Protection des données personnelles dans le cloud public.",
    "ISO/IEC 27701 : Extension vie privée / RGPD de l’ISO 27001.",
    "ISO/IEC 22301 : Continuité d’activité face à des crises et incidents majeurs.",
    "ISO/IEC 31000 : Cadre général de risk management pour tout type d’organisation.",
    "ISO/IEC 62443 : Sécurisation spécifique des systèmes de contrôle industriel (ICS/SCADA).",
    "COBIT 2019 : Gouvernance IT alignée sur les objectifs métiers, risques et audits.",
    "NIST SP 800-53 : Catalogue de contrôles pour les systèmes d’information fédéraux US.",
    "NIST SP 800-37 : Processus de gestion des risques et autorisation à opérer (ATO).",
    "NIST Cybersecurity Framework : Cadre « Identifier, Protéger, Détecter, Répondre, Récupérer ».",
    "PCI DSS : Sécurisation des données de carte bancaire (Visa, MasterCard, etc.).",
    "RGPD (GDPR) : Règlement européen imposant la protection des données personnelles.",
    "DORA : Résilience numérique obligatoire pour le secteur financier européen.",
    "NIS2 : Directive européenne élargie pour la cybersécurité des réseaux et systèmes essentiels.",
    "eIDAS : Règlement sur l’identification électronique et les services de confiance (signatures).",
    "ePrivacy Directive : Confidentialité des communications électroniques et cookies au sein de l’UE.",
    "EBA Guidelines (ICT & Security) : Bonnes pratiques de cybersécurité pour le secteur bancaire UE.",
    "LPM (France) : Sécurité renforcée pour les Opérateurs d’Importance Vitale en France.",
    "Loi pour une République Numérique (France) : Droits numériques et ouverture des données publiques.",
    "CNIL (France) : Recommandations et sanctions en matière de protection des données personnelles.",
    "Projet de Loi Résilience (France) : Renforcement de la résilience numérique des services critiques.",
    "CJIS Security Policy (USA) : Protection des données de justice et police (FBI).",
    "CMMC (USA) : Certification de maturité cyber pour les sous-traitants de la Défense US.",
    "FISMA (USA) : Loi imposant un niveau de sécurité pour les systèmes d’information fédéraux.",
    "FedRAMP (USA) : Autorisation gouvernementale pour les fournisseurs cloud fédéraux.",
    "HIPAA (USA) : Confidentialité et sécurité des données de santé aux États-Unis.",
    "HITECH (USA) : Extension de HIPAA, notification obligatoire des violations de données médicales.",
    "Sarbanes-Oxley Act Section 404 : Contrôles internes robustes sur l’information financière.",
    "Basel III (Sécurité IT) : Normes bancaires internationales incluant la gestion des risques IT.",
    "PSD2 (UE) : Directive sur les services de paiement et l’authentification forte (SCA).",
    "BDSG (Allemagne) : Loi allemande de protection des données, complémentaire au RGPD.",
    "UK Data Protection Act 2018 : Loi post-RGPD au Royaume-Uni, maintien du niveau de protection.",
    "LGPD (Brésil) : Loi brésilienne inspirée du RGPD, protection des données des résidents brésiliens.",
    "PIPL (Chine) : Cadre légal sur la collecte et le traitement des données personnelles en Chine.",
    "Cybersecurity Law of China : Loi imposant la localisation des données et un contrôle étatique fort.",
    "PDPA (Singapour) : Loi de protection des données personnelles à Singapour.",
    "POPIA (Afrique du Sud) : Cadre légal de protection des données personnelles en Afrique du Sud.",
    "ANSSI Référentiels (France) : Guides et labels de l’agence nationale de cybersécurité française.",
    "ENISA Cybersecurity Act (UE) : Mandat étendu pour l’ENISA et schémas de certification cybersécurité.",
    "ePrivacy Regulation (UE, projet) : Réglementation à venir sur la vie privée en ligne.",
    "ICS-CERT Guidelines (USA) : Mesures de cybersécurité pour systèmes industriels et SCADA.",
    "FIPS 140-3 (USA) : Validation cryptographique pour modules utilisés par le gouvernement US.",
    "ISAE 3402 : Norme internationale d’audit des contrôles internes chez les prestataires de services.",
    "SOC 2 (AICPA) : Audit sur la sécurité, la disponibilité, l’intégrité, la confidentialité et la vie privée.",
    "TISAX (Allemagne) : Évaluation de la sécurité de l’information pour l’industrie automobile.",
    "WLA-SCS : Standard de la World Lottery Association pour la sécurité des jeux de loterie.",
    "CCPA/CPRA (Californie, USA) : Lois californiennes rapprochant les standards de confidentialité du RGPD."
]

def write_csv_and_descriptions(data, desc_list, csv_filename="normes_reglementations.csv"):
    """
    Écrit le tableau dans un fichier CSV puis ajoute en bas (après quelques lignes vides)
    la liste des descriptions textuelles associées. 
    """
    fieldnames = list(data[0].keys())
    
    with open(csv_filename, mode='w', newline='', encoding='utf-8') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter=';')
        writer.writeheader()
        
        for row in data:
            writer.writerow(row)
            
        csvfile.write("\n\n# Descriptions des normes / réglementations :\n")
        
        for d in desc_list:
            csvfile.write(d + "\n")


write_csv_and_descriptions(data_table, descriptions, csv_filename="normes_reglementations.csv")
input("Fichier CSV 'normes_reglementations.csv' généré avec succès !\nAppuyez sur Entrée pour quitter.")